### ISSUE TITLE
【生态工具测试】【Terraform】【provider文档问题】华为云provider DNS资源中， 创建内网Zone的属性router，类型错误。

### ISSUE THREAD

**Issue by h00454348** [edisonxiang/community#1]
问题现象：
huaweicloud provider DNS资源中， 创建内网Zone的属性router，类型为list，类型错误。
定位结果：
查询了创建内网DNS的接口，router属性的类型应该为对象类型。
修改建议：
将router的类型修改为对象类型，去掉中括号。

**Comment by niuzhenguo** [comment]
https://github.com/terraform-providers/terraform-provider-huaweicloud/pull/67
