### ISSUE TITLE
【terraform测试】【OTC provider】在s3资源中，resource "opentelekomcloud_s3_bucket" ，使用lifecycle_rule 中的tags参数时，提示tags无效。

### ISSUE THREAD

**Issue by h00454348** [edisonxiang/community#12]
【测试环境】
DT类生产
【问题描述】
在OTCprovider 中，使用opentelekomcloud_s3_bucket资源创建bucket时，使用lifecycle_rule 中的tags参数时，提示tags invalid or unknown。
【问题定位】
代码里未写，请修改。

**Comment by niuzhenguo** [comment]
代码已提交

**Comment by h00454348** [comment]
在最新文档中已删除lifecycle_rule 中tags参数。
