### ISSUE TITLE
【terraform测试】【DT类生产】【smn资源】使用terraform创建SMN topic时，报Resource not found错误。

### ISSUE THREAD

**Issue by h00454348** [edisonxiang/community#13]
【测试环境】
DT类生产
 【问题现象】
 创建SMN topic时，报Resource not found错误。
 【定位原因】
 在DT类生产创建smn的请求endpoint是替换的computer的，在替换过程中出错（/v2.1/b730519ca7064da2a3233e86bee139e4/notifications/topics HTTP/1.1），导致API not found。
 【解决建议】
 换成直接从endpoint提取，而不是替换computer的endpoint方式。

**Comment by niuzhenguo** [comment]
代码已合入

**Comment by h00454348** [comment]
已在类生产上测试，测试版本为1.6.0
