### ISSUE TITLE
【terraform测试】【OTCprovider】【DCS资源】根据provider文档，使用terraform对DCS资源进行必选参数测试时，必选参数校验未通过。

### ISSUE THREAD

**Issue by h00454348** [edisonxiang/community#17]
【测试环境】
DT类生产
【问题现象】
1.使用terraform对DCS资源进行必选参数测试时，报backup_at、backup_type、begin_at、engine、period_type、save_days这几个参数报“required field is not set ”问题。必选参数校验未通过，应在provider文档中将这几个参数从可选改为必选（和OTC现网接口文档保持一致）。
2.在provider文档中，DCS资源中的engine参数，目前只支持Redis，将engine参数当前不支持的rabbitmq and kafka去掉。

**Comment by niuzhenguo** [comment]
已修改

**Comment by h00454348** [comment]
已测试，这个几个参数必选校验通过，测试版本1.6.0
