### ISSUE TITLE
【生态工具测试】【Terraform】【接口不支持问题】给增强型lb绑定Eip，暂时不支持。

### ISSUE THREAD

**Issue by h00454348** [edisonxiang/community#2]
测试环境：
DT和HEC
问题现象：
使用terraform给增强型lb绑定Eip，暂时不支持。
问题定位：
目前networking_floatingip_associate_v2代码已编写，未上线，会持续跟踪。

**Comment by h00454348** [comment]
opentelekomcloud provider 已支持networking_floatingip_associate_v2资源，已完成ELB绑定EIP。HuaweiCloud provider暂未支持。

**Comment by niuzhenguo** [comment]
huaweicloud已经release

**Comment by h00454348** [comment]
HuaweiCloud 版本在 v1.3.0版本中已支持networking_floatingip_associate_v2资源，provider文档已更新，已完成测试，成功给增强型ELB绑定EIP。
