### ISSUE TITLE
【terraform测试】【CCE资源】【OTCprovider】创建CCE资源时，cluster_version参数说明中版本与OTC现网支持版本不一致，创建时报版本不支持错误。

### ISSUE THREAD

**Issue by h00454348** [edisonxiang/community#20]
【测试环境】
OTC现网
【问题现象】
1.cluster_version目前支持版本为：v1.9.2-r2 or v1.11.3-r1，对于版本会更新的参数，可以采取查接口文档的方式给出。
2.修改cluster_version版本时，会重新创建新资源，文档中未说明。

**Comment by niuzhenguo** [comment]
代码已合入

**Comment by h00454348** [comment]
文档已修改。
