### ISSUE TITLE
【terraform测试】【DT类生产】【CCE资源】使用terraform创建CCE 集群时，报Resource not found错误。 

### ISSUE THREAD

**Issue by h00454348** [edisonxiang/community#21]
【测试环境】
DT类生产
【定位原因】
在DT类生产创建CCE 集群的请求endpoint是替换的computer的，在替换过程中出错（/api/v3/projects.1/b730519ca7064da2a3233e86bee139e4/clusters HTTP/1.1），导致API not found。

**Comment by niuzhenguo** [comment]
代码已合入

**Comment by h00454348** [comment]
Api接口已成功调用，目前是现网的域名和DT类生产的域名不一致，导致在接口调用过程中，API找不到。
