### ISSUE TITLE
【terraform测试】【OTCprovider】【RTS资源】使用AK/SK认证，创建RTS时，有个GET请求授权失败。

### ISSUE THREAD

**Issue by h00454348** [edisonxiang/community#29]

**Comment by h00454348** [comment]
【测试环境】
DT类生产
【问题原因】
在使用terraform创建RTS资源时，在访问GET /v1/b730519ca7064da2a3233e86bee139e4/stacks/rts_test1 HTTP/1.1这个请求时，重定向到GET /v1/b730519ca7064da2a3233e86bee139e4/stacks/rts_test1/df473a8e-75b4-42a2-bc7b-6b687a6934f5，导致与API网关计算出来的签名不一致，报授权失败。

**Comment by niuzhenguo** [comment]
代码已合入

**Comment by h00454348** [comment]
已测试，测试版本1.6.0
