### ISSUE TITLE
【terraform测试】【OTC provider】【DCS资源】创建DCS资源，进行必选参数测试试，报passwd和engine_version 未设置。

### ISSUE THREAD

**Issue by h00454348** [edisonxiang/community#34]
【测试环境】
DT类生产
【问题原因】
查看了接口文档，passwd和engine_version 是必选参数，应该在文档中说明，并加上必选参数校验。

**Comment by zhongjun2** [comment]
代码已提交: https://github.com/terraform-providers/terraform-provider-opentelekomcloud/pull/217

**Comment by niuzhenguo** [comment]
代码已合入
