### ISSUE TITLE
【Terraform】【OTCprovider】【output】server group 的output文档中没有ID，实际上可以输出，请修改帮助文档

### ISSUE THREAD

**Issue by zhangfan133** [edisonxiang/community#40]
【Terraform】【OTCprovider】【output】server group 的output文档中没有ID，实际上可以输出，请修改帮助文档

相关资源：OTCprovider
地址：https://www.terraform.io/docs/providers/huaweicloud/r/compute_servergroup_v2.html
问题：需要输出servergroup 的id

**Comment by niuzhenguo** [comment]
代码已合入
