### ISSUE TITLE
【Terraform】【OTCprovider】【output】联邦用户只有临时token或者临时AK+SK+sercuritytoken，在利用otc provider进行OBS资源申请时，无法执行命令

### ISSUE THREAD

**Issue by zhangfan133** [edisonxiang/community#41]
联邦用户只有临时token或者临时AK+SK+sercuritytoken，在利用otc provider进行OBS资源申请时，无法执行命令。

功能缺失。

1. otc provider仅支持token、username+pasword、AK+SK三种认证方式；
2. 联邦用户只有临时token或者临时**AK+SK+sercuritytoken**；
3. OBS不支持使用token;
4. 因此需要有AK+SK+sercuritytoken的认证方式

**Comment by niuzhenguo** [comment]
security_token support already released with v1.8.0
