### ISSUE TITLE
【Terraform】【OTCprovider】【DMS】申请DMS实例参数填错的情况下，返回500信息中包含Telefonica信息

### ISSUE THREAD

**Issue by zhangfan133** [edisonxiang/community#43]
申请DMS实例参数填错的情况下，返回500信息中包含Telefonica信息

1. DMS中的max_consume_count中将int写错为string；

2. 报错 信息中包含telefornica信息

期望：不应该出现其他provider信息

**Comment by niuzhenguo** [comment]
已修改
