### ISSUE TITLE
【terraform测试】【DT类生产】【kms服务】执行客户脚本时，创建KMS时，报Resource not found错误。

### ISSUE THREAD

**Issue by h00454348** [edisonxiang/community#7]
【测试环境】
 DT类生产
【问题现象】
 执行客户脚本，创建KMS时，报Resource not found错误。
【定位原因】
 在DT类生产创建KMS的请求endpoint是替换的ECS的，在替换过程中出错（/v1.0.b730519ca7064da2a3233e86bee139e4/kms/create-key HTTP/1.1），导致API not found。
【解决建议】
  换成直接从endpoint提取，而不是替换ecs endpoint方式。

**Comment by niuzhenguo** [comment]
代码已提交，等release

**Comment by h00454348** [comment]
在OTC provider 1.5.2版本中，已测试，在DT类生产已成功创建KMS。
