### ISSUE TITLE
【terraform测试】【OTC现网】【DNS服务】更新DNS  record set时，更新报错，报请求无效。

### ISSUE THREAD

**Issue by h00454348** [edisonxiang/community#9]
【测试环境】
DT类生产
【问题现象】
使用terraform更新DNS  record set时，更新报错，报请求无效。
【问题定位】
问题已定位，请修改。

**Comment by niuzhenguo** [comment]
已修改，等release

**Comment by h00454348** [comment]
在OTC现网上使用OTCprovider1.5.2版本已测试，问题已修复。
